version: '2'

services:
    node:
        build: .

    nginx:
        image: nginx:1.23.1
        ports:
            - "8000:8000"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - node
